### ISSUE TITLE
Remove setup.py - broken build process

### ISSUE THREAD

**Issue by osh** [pysdr/pysdruhd#2]
the cmake build and install works fine ---
unfortunately its not clear cmake is intended to be used since there is a setup.py that builds and installs without error but has broken linkage
running with the broken setup.py produces module produces the following output

```
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysdruhd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/pysdruhd.so: undefined symbol: subdev_from_spec
```

**Comment by 777arc** [comment]
Ah, yeah I created setup.py in an attempt to get this thing working in Python 3, and at one point it was working using setup.py but not cmake (go figure).  Yeah I'll remove it for now.
